name: Semgrep
on:
  push:
    branches: [master]
jobs:
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Semgrep
      id: semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: r/all
